### ISSUE TITLE
Handling NaN values

### ISSUE THREAD

**Issue by marchezinixd** [hafen/stlplus#2]
Hi,
I was searching about decompose functions that could handle NaNs and found yours, but it is implemented in R, would be possible for you to give me a brief explanation how you handle the NaNs so i can understand how it works, use it and also try to implement in python?
Thanks

**Comment by hafen** [comment]
Sure. Basically, loess is used in nearly all steps of the algorithm, and the loess algorithm handles missing values by using nearest neighbors. With complete data, if you are using loess to fit a regular time series at time t_k and your window width is 11, you use the 5 observations to the left of t_k and the 5 observations to the right. If any of those observations are missing, loess will continue to go out to the left or right until it has the correct number of non-NA nearest neighbors. I see the Python statsmodels module has a "lowess" function, but I can't speak to how well it works and whether it has been implemented to deal with missing values (and several other features of the newer "loess" approach which allows the degree of polynomial to vary and for weights to be specified, etc.).

**Comment by marchezinixd** [comment]
Thanks for the explanation, it was very helpfull. I found a library to compile R inside python and i'm using your library.
thanks.
